export const webFontFamily = {
  'Poppins-Bold': 'Poppins-Bold',
  'Poppins-BoldItalic': 'Poppins-BoldItalic',
  'Poppins-ExtraBold': 'Poppins-ExtraBold',
  'Poppins-ExtraBoldItalic': 'Poppins-ExtraBoldItalic',
  'Poppins-ExtraLight': 'Poppins-ExtraLight',
  'Poppins-ExtraLightItalic': 'Poppins-ExtraLightItalic',
  'Poppins-Italic': 'Poppins-Italic',
  'Poppins-Light': 'Poppins-Light',
  'Poppins-LightItalic': 'Poppins-LightItalic',
  'Poppins-Medium': 'Poppins-Medium',
  'Poppins-MediumItalic': 'Poppins-MediumItalic',
  'Poppins-Regular': 'Poppins-Regular',
  'Poppins-SemiBold': 'Poppins-SemiBold',
  'Poppins-SemiBoldItalic': 'Poppins-SemiBoldItalic',
  'Poppins-Thin': 'Poppins-Thin',
  'Poppins-ThinItalic': 'Poppins-ThinItalic',
  'Urbanist-LightItalic': 'Urbanist-LightItalic',
  'Urbanist-Medium': 'Urbanist-Medium',
  'Urbanist-MediumItalic': 'Urbanist-MediumItalic',
  'Urbanist-Regular': 'Urbanist-Regular',
  'Urbanist-RegularItalic': 'Urbanist-RegularItalic',
  'Urbanist-SemiBold': 'Urbanist-SemiBold',
  'Urbanist-SemiBoldItalic': 'Urbanist-SemiBoldItalic',
  'Urbanist-Thin': 'Urbanist-Thin',
  'Urbanist-ThinItalic': 'Urbanist-ThinItalic',
  'Urbanist-Bold': 'Urbanist-Bold',

  'HelveticaNeueLTArabic55-Roman': 'HelveticaNeueLTArabic55-Roman',
  'HelveticaNeueLTArabic45-Light': 'HelveticaNeueLTArabic45-Light',
  'HelveticaNeueLTArabic75-Bold': 'HelveticaNeueLTArabic75-Bold',
};
