import React from 'react';
import { webFontFamily } from './fonts';

export const typography = {
  headings: {
    en: {
      h1: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '35px',
        lineHeight: '51px',
      } as React.CSSProperties,
      h2: {
        fontFamily: webFontFamily['PlusJakartaSans-SemiBold'],
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '25px',
        lineHeight: '30px',
      } as React.CSSProperties,
      h3: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '24px',
        lineHeight: '29px',
      } as React.CSSProperties,
      h4: {
        FontFamily: webFontFamily['PlusJakartaSans-SemiBold'],
        FontStyle: 'Semi Bold',
        FontSize: '20px',
        LineHeight: '24px',
        fontWeight: 600,
      } as React.CSSProperties,
      h5: {
        FontFamily: webFontFamily['PlusJakartaSans-Bold'],
        FontStyle: 'Bold',
        FontSize: '20px',
        LineHeight: '24px',
        fontWeight: 700,
      } as React.CSSProperties,
      h6: {
        FontFamily: webFontFamily['PlusJakartaSans-SemiBold'],
        FontStyle: 'Semi Bold',
        FontSize: '18px',
        LineHeight: '22px',
        fontWeight: 600,
      } as React.CSSProperties,
    },
    ar: {
      h1: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '50px',
        lineHeight: '63px',
      } as React.CSSProperties,
      h2: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontStyle: 'Bold',
        fontWeight: 700,
        fontSize: ' 40px',
        lineHeight: '33px',
      } as React.CSSProperties,
      h3: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontSize: '36px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '54px',
      } as React.CSSProperties,
      h4: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontStyle: 'Bold',
        fontSize: '34px',
        lineHeight: '28px',
        fontWeight: 700,
      } as React.CSSProperties,

      h5: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '28px',
        lineHeight: '42px',
      } as React.CSSProperties,
    },
  } ,
  paragraph: {
    en: {
      p1: {
        fontFamily: webFontFamily['PlusJakartaSans-Regular'],
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '16px',
        lineHeight: '15px',
      } as React.CSSProperties,
      p2: {
        FontFamily: webFontFamily['PlusJakartaSans-Regular'],
        FontStyle: 'Regular',
        FontSize: '15px',
        LineHeight: '24px',
        fontWeight: 400,
      } as React.CSSProperties,
      p3: {
        fontFamily: webFontFamily['PlusJakartaSans-Regular'],
        fontStyle: 'normal',
        fontWeight: 500,
        fontSize: '14px',
        lineHeight: '17px',
      } as React.CSSProperties,
      p4: {
        FontFamily: webFontFamily['PlusJakartaSans-Regular'],
        FontStyle: 'Regular',
        FontSize: '14px',
        LineHeight: '27px',
        fontWeight: 400,
      } as React.CSSProperties,
    },
    ar: {
      p1: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '64px',
        lineHeight: '67px',
      } as React.CSSProperties,
      p2: {
        fontFamily: webFontFamily['PlusJakartaSans-Medium'],
        fontStyle: 'normal',
        fontWeight: 500,
        fontSize: '34px',
        lineHeight: '43px',
      } as React.CSSProperties,
      p3: {
        fontFamily: webFontFamily['PlusJakartaSans-Medium'],
        fontStyle: 'normal',
        fontWeight: 500,
        fontSize: '20px',
        lineHeight: '37px',
      } as React.CSSProperties,
      p4: {
        fontFamily: webFontFamily['PlusJakartaSans-Medium'],
        fontStyle: 'Medium',
        fontSize: '18px',
        lineHeight: '31px',
        fontWeight: 500,
      } as React.CSSProperties,
    },
  } ,
  buttonText: {
    en: {
      b1: {
        FontFamily: webFontFamily['PlusJakartaSans-SemiBold'],
        FontStyle: 'Semi Bold',
        FontSize: '14px',
        fontWeight: 600,
        LineHeight: '17px',
      } as React.CSSProperties,
      b2: {
        FontFamily: webFontFamily['PlusJakartaSans-Regular'],
        FontStyle: 'Medium',
        FontSize: '16px',
        fontWeight: 500,
        LineHeight: '15px',
      } as React.CSSProperties,
      b3: {
        FontFamily: 'Inter',
        FontStyle: 'Regular',
        FontSize: '14px',
        LineHeight: '17px',
        fontWeight: 400,
      } as React.CSSProperties,
    },
    ar: {
      b1: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontStyle: 'normal',
        fontSize: '22px',
        lineHeight: '28px',
        fontWeight: 700,
      } as React.CSSProperties,
      b2: {
        fontFamily: webFontFamily['PlusJakartaSans-SemiBold'],
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '18px',
        lineHeight: '27px',
      } as React.CSSProperties,
      b3: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontStyle: 'Bold',
        fontSize: '16px',
        lineHeight: '20px',
        fontWeight: 700,
      } as React.CSSProperties,
    },
  },
  label: {
    en: {
      l1: {
        FontFamily: webFontFamily['PlusJakartaSans-Regular'],
        FontStyle: 'Regular',
        FontSize: '14px',
        LineHeight: '17px',
        fontWeight: 400,
      } as React.CSSProperties,
      l2: {
        FontFamily: webFontFamily['PlusJakartaSans-Regular'],
        FontStyle: 'Mixed',
        FontSize: '16px',
        LineHeight: '15px',
        fontWeight: 400,
      } as React.CSSProperties,
      l3: {
        FontFamily: webFontFamily['PlusJakartaSans-Regular'],
        FontStyle: 'Medium',
        FontSize: '16px',
        LineHeight: '19px',
        fontWeight: 500,
      } as React.CSSProperties,
      l4: {
        FontFamily: webFontFamily['PlusJakartaSans-SemiBold'],
        FontStyle: 'Semi Bold',
        FontSize: '16px',
        LineHeight: '19px',
        fontWeight: 600,
      } as React.CSSProperties,
    },
    ar: {
      l1: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '40px',
        lineHeight: '50px',
      } as React.CSSProperties,
      l2: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '36px',
        lineHeight: '54px',
      } as React.CSSProperties,
      l3: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontStyle: 'Bold',
        fontSize: '32px',
        lineHeight: '40px',
        fontWeight: 700,
      } as React.CSSProperties,
      l4: {
        fontFamily: webFontFamily['PlusJakartaSans-Bold'],
        fontStyle: 'Bold',
        fontSize: '26px',
        lineHeight: '33px',
        fontWeight: 700,
      } as React.CSSProperties,
    },
  } ,
  inputfieldText: {
    en: {
      i1: {
        FontFamily: webFontFamily['PlusJakartaSans-Regular'],
        FontStyle: 'Medium',
        FontSize: '15px',
        LineHeight: '18px',
        fontWeight: 500,
      } as React.CSSProperties,
      i2: {
        FontFamily: webFontFamily['PlusJakartaSans-Regular'],
        FontStyle: 'Regular',
        FontSize: '15px',
        LineHeight: '18px',
        fontWeight: 400,
      } as React.CSSProperties,
    },
    ar: {
      i1: {
        fontFamily: webFontFamily['PlusJakartaSans-Regular'],
        fontStyle: 'normal',
        fontSize: '16px',
        lineHeight: '31px',
        fontHeight: 500,
      } as React.CSSProperties,
      i2: {
        fontFamily: webFontFamily['PlusJakartaSans-Regular'],
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '16px',
        lineHeight: '20px',
      } as React.CSSProperties,
    },
  } ,
};
