import React from 'react';
import { webFontFamily } from './fonts';

export const typography: any = {
  headings: {
    en: {
      h1: {
        fontFamily: webFontFamily['Poppins-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '35px',
        lineHeight: '51px',
      } as React.CSSProperties,
      h2: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '25px',
        lineHeight: '30px',
        letterSpacing: '0.62px',
      } as React.CSSProperties,
      h3: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '48px',
        lineHeight: 'normal',
      } as React.CSSProperties,
      h4: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '20px',
        lineHeight: '24px',
        fontWeight: 600,
      } as React.CSSProperties,
      h5: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'Bold',
        fontSize: '20px',
        lineHeight: '24px',
        fontWeight: 700,
      } as React.CSSProperties,
      h6: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'normal',
        fontSize: '40px',
        lineHeight: 'normal',
        fontWeight: 700,
      } as React.CSSProperties,
      h7: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '16px',
        lineHeight: '24px',
        fontWeight: 600,
        letterSpacing: '0.13px',
      } as React.CSSProperties,
      h10: {
        fontFamily: webFontFamily['Lato-Regular'],
        fontStyle: 'normal',
        fontSize: '20px',
        fontWeight: 600,
        lineHeight: '30px',
      } as React.CSSProperties,
      h8: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'normal',
        fontSize: '24px',
        lineHeight: 'normal',
        fontWeight: 700,
      } as React.CSSProperties,
      h9: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'normal',
        fontSize: '26px',
        lineHeight: 'normal',
        fontWeight: 400,
      } as React.CSSProperties,
    },
    ar: {
      h1: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '35px',
        lineHeight: '51px',
      } as React.CSSProperties,
      h2: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'Bold',
        fontWeight: 700,
        fontSize: ' 40px',
        lineHeight: '33px',
      } as React.CSSProperties,
      h3: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontSize: '22px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '30px',
      } as React.CSSProperties,
      h4: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'normal',
        fontSize: '40px',
        lineHeight: 'normal',
        fontWeight: 700,
      } as React.CSSProperties,
      h5: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '28px',
        lineHeight: '42px',
      } as React.CSSProperties,
      h6: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '16px',
        lineHeight: '22px',
        fontWeight: 600,
      } as React.CSSProperties,
      h7: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'normal',
        fontSize: '24px',
        lineHeight: 'normal',
        fontWeight: 700,
      } as React.CSSProperties,
      h8: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '28px',
        lineHeight: '42px',
      } as React.CSSProperties,
      h9: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '28px',
        lineHeight: '42px',
      } as React.CSSProperties,
      h11: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '28px',
        lineHeight: '42px',
      } as React.CSSProperties,
      h12: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '26px',
        lineHeight: '31px',
        fontWeight: 500,
      } as React.CSSProperties,
    },
  },
  paragraph: {
    en: {
      p1: {
        fontFamily: webFontFamily['Poppins-Bold'],
        fontSize: '20px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: 'normal',
      } as React.CSSProperties,
      'p1.5': {
        fontFamily: webFontFamily['Lato-Regular'],
        fontStyle: 'normal',
        fontSize: '16px',
        lineHeight: '30px',
        fontWeight: 400,
      } as React.CSSProperties,
      p2: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '17px',
        lineHeight: 'normal',
      } as React.CSSProperties,
      p4: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Regular',
        fontSize: '14px',
        lineHeight: '27px',
        fontWeight: 400,
      } as React.CSSProperties,
      p5: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Regular',
        fontSize: '14px',
        lineHeight: '27px',
        fontWeight: 600,
      } as React.CSSProperties,
      p6: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Regular',
        fontSize: '16px',
        lineHeight: '32px',
        fontWeight: 400,
      } as React.CSSProperties,
      p7: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'normal',
        fontSize: '150px',
        lineHeight: 'normal',
        fontWeight: 700,
      } as React.CSSProperties,
    },
    ar: {
      p1: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '16px',
        lineHeight: '25px',
      } as React.CSSProperties,
      'p1.5': {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Regular',
        fontSize: '16px',
        lineHeight: '21px',
        fontWeight: 400,
      } as React.CSSProperties,
      p2: {
        fontFamily: webFontFamily['Urbanist-Medium'],
        fontStyle: 'normal',
        fontWeight: 500,
        fontSize: '14px',
        lineHeight: '17px',
      } as React.CSSProperties,
      p3: {
        fontFamily: webFontFamily['Urbanist-Medium'],
        fontStyle: 'normal',
        fontWeight: 500,
        fontSize: '12px',
        lineHeight: '14px',
      } as React.CSSProperties,
      p4: {
        fontFamily: webFontFamily['Urbanist-Medium'],
        fontStyle: 'Medium',
        fontSize: '18px',
        lineHeight: '31px',
        fontWeight: 500,
      } as React.CSSProperties,
      p5: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'normal',
        fontSize: '14px',
        lineHeight: 'normal',
        fontWeight: 600,
      } as React.CSSProperties,
      p6: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Regular',
        fontSize: '16px',
        lineHeight: '32px',
        fontWeight: 400,
      } as React.CSSProperties,
      p7: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'normal',
        fontSize: '150px',
        lineHeight: 'normal',
        fontWeight: 700,
      } as React.CSSProperties,
    },
  },
  buttonText: {
    en: {
      b1: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '14px',
        fontWeight: 600,
        lineHeight: '17px',
      } as React.CSSProperties,
      b2: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'normal',
        fontSize: '15px',
        fontWeight: 700,
        lineHeight: 'normal',
      } as React.CSSProperties,
      b3: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Regular',
        fontSize: '14px',
        lineHeight: '17px',
        fontWeight: 400,
      } as React.CSSProperties,
      b4: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '15px',
        fontWeight: 600,
        lineHeight: '15px',
      } as React.CSSProperties,
    },
    ar: {
      b1: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'normal',
        fontSize: '22px',
        lineHeight: '28px',
        fontWeight: 700,
      } as React.CSSProperties,
      b2: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '18px',
        lineHeight: '27px',
      } as React.CSSProperties,
      b3: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'Bold',
        fontSize: '16px',
        lineHeight: '20px',
        fontWeight: 700,
      } as React.CSSProperties,
      b4: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'Bold',
        fontSize: '14px',
        lineHeight: '30px',
        fontWeight: 600,
      } as React.CSSProperties,
    },
  },
  label: {
    en: {
      l1: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Regular',
        fontSize: '14px',
        lineHeight: '17px',
        fontWeight: 400,
        letterSpacing: '0.96px',
      } as React.CSSProperties,
      l2: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Mixed',
        fontSize: '16px',
        lineHeight: '15px',
        fontWeight: 400,
      } as React.CSSProperties,
      l3: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Medium',
        fontSize: '16px',
        lineHeight: '19px',
        fontWeight: 500,
      } as React.CSSProperties,
      l4: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '16px',
        lineHeight: '19px',
        fontWeight: 600,
      } as React.CSSProperties,
      l5: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '15px',
        lineHeight: '24px',
        fontWeight: 500,
      } as React.CSSProperties,
      l6: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '17px',
        lineHeight: '16px',
        fontWeight: 600,
      } as React.CSSProperties,
      l7: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '15px',
        lineHeight: '18px',
        fontWeight: 700,
      } as React.CSSProperties,
      l8: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '22px',
        lineHeight: '26px',
        fontWeight: 700,
      } as React.CSSProperties,
      l9: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '16px',
        lineHeight: '27px',
        fontWeight: 600,
      } as React.CSSProperties,
      l10: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'normal',
        fontSize: '60px',
        lineHeight: '83px',
        fontWeight: 600,
      } as React.CSSProperties,
      l11: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'normal',
        fontSize: '13px',
        lineHeight: '15.73px',
        fontWeight: 400,
      } as React.CSSProperties,
      l12: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'normal',
        fontSize: '14px',
        lineHeight: '12px',
        fontWeight: 400,
      } as React.CSSProperties,
    },
    ar: {
      l1: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Regular',
        fontSize: '14px',
        lineHeight: '17px',
        fontWeight: 400,
      } as React.CSSProperties,
      l2: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '36px',
        lineHeight: '54px',
      } as React.CSSProperties,
      l3: {
        fontFamily: webFontFamily['Urbanist-Bold'],
        fontStyle: 'Bold',
        fontSize: '32px',
        lineHeight: '40px',
        fontWeight: 700,
      } as React.CSSProperties,
      l4: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '16px',
        lineHeight: '19px',
        fontWeight: 600,
      } as React.CSSProperties,
      l5: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '15px',
        lineHeight: '24px',
        fontWeight: 500,
      } as React.CSSProperties,
      l6: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '17px',
        lineHeight: '16px',
        fontWeight: 600,
      } as React.CSSProperties,
      l7: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '15px',
        lineHeight: '18px',
        fontWeight: 700,
      } as React.CSSProperties,
      l8: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '22px',
        lineHeight: '26px',
        fontWeight: 700,
      } as React.CSSProperties,
      l9: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '16px',
        lineHeight: '27px',
        fontWeight: 600,
      } as React.CSSProperties,
      l10: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'Semi Bold',
        fontSize: '60px',
        lineHeight: '72px',
        fontWeight: 600,
      } as React.CSSProperties,
      l11: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'normal',
        fontSize: '13px',
        lineHeight: '15.73px',
        fontWeight: 400,
      } as React.CSSProperties,
      l12: {
        fontFamily: webFontFamily['Urbanist-SemiBold'],
        fontStyle: 'normal',
        fontSize: '10px',
        lineHeight: '12px',
        fontWeight: 400,
      } as React.CSSProperties,
    },
  },
  inputFieldText: {
    en: {
      i1: {
        fontFamily: webFontFamily['Lato-Regular'],
        fontStyle: 'normal',
        fontSize: '15px',
        lineHeight: 'normal',
        fontWeight: 500,
      } as React.CSSProperties,
      i2: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Regular',
        fontSize: '15px',
        lineHeight: '18px',
        fontWeight: 400,
      } as React.CSSProperties,
      i3: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Bold',
        fontSize: '16px',
        lineHeight: '16px',
        fontWeight: 600,
      } as React.CSSProperties,
      i4: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Bold',
        fontSize: '12px',
        lineHeight: '14px',
        fontWeight: 500,
      } as React.CSSProperties,
    },
    ar: {
      i1: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'normal',
        fontSize: '16px',
        lineHeight: '31px',
        fontHeight: 500,
      } as React.CSSProperties,
      i2: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '16px',
        lineHeight: '20px',
      } as React.CSSProperties,
      i3: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Bold',
        fontSize: '16px',
        lineHeight: '16px',
        fontWeight: 600,
      } as React.CSSProperties,
      i4: {
        fontFamily: webFontFamily['Urbanist-Regular'],
        fontStyle: 'Bold',
        fontSize: '12px',
        lineHeight: '14px',
        fontWeight: 500,
      } as React.CSSProperties,
    },
  },
};
